name: Python package

on:
  push:
    branches: [ master, ci_changes ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      CMAKE_GENERATOR: Ninja
      CC: gcc-9
      CXX: g++-9

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Set up C++
      run: |
        sudo apt-get -y install ninja-build
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get -y install gfortran
        fi
        python -m pip install --upgrade pip
        pip install maturin
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg install pybind11
      shell: bash
    - name: Configure
      run: mkdir build && cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
      shell: bash
    - name: Build
      run: cmake --build build --config Release
      shell: bash
